 # Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC2
  hosts: webservers
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup